name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing request for this?
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched the existing issues and this is a new feature request
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I also considered..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Filters & Discovery
        - Catalog Management
        - User Interface
        - Configuration
        - API / Backend
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical - blocking my use
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or links to similar implementations

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
