export const IMDB_SORT_OPTIONS = [
  { value: 'rating', label: '⭐ Highest Rated' },
  { value: 'votes', label: '🗳️ Most Votes' },
];

export const IMDB_REGION_LABELS: Record<string, string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BN: 'Brunei',
  BO: 'Bolivia',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CD: 'DR Congo',
  CH: 'Switzerland',
  CI: 'Ivory Coast',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DK: 'Denmark',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GB: 'United Kingdom',
  GE: 'Georgia',
  GH: 'Ghana',
  GR: 'Greece',
  GT: 'Guatemala',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KR: 'South Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LK: 'Sri Lanka',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macau',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PR: 'Puerto Rico',
  PS: 'Palestine',
  PT: 'Portugal',
  PY: 'Paraguay',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SN: 'Senegal',
  SO: 'Somalia',
  SY: 'Syria',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  XWG: 'West Germany',
  XWW: 'Worldwide',
  CSHH: 'Czechoslovakia',
  SUHH: 'Soviet Union',
  XYU: 'Yugoslavia',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export const IMDB_PRESET_CATALOGS = {
  movie: [
    {
      value: 'top-rated-movies',
      label: '⭐ IMDB Top Rated Movies',
      description: 'Top rated movies from IMDB dataset',
      config: { type: 'movie', sortBy: 'rating', name: 'IMDB Top Rated Movies' },
    },
    {
      value: 'most-voted-movies',
      label: '🗳️ Most Voted Movies',
      description: 'Most voted movies on IMDB',
      config: { type: 'movie', sortBy: 'votes', name: 'IMDB Most Voted Movies' },
    },
    {
      value: 'top-rated-india-movies',
      label: '🇮🇳 Top Rated in India',
      description: 'Top rated movies released in India',
      config: {
        type: 'movie',
        sortBy: 'rating',
        region: 'IN',
        name: 'IMDB Top Rated India Movies',
      },
    },
    {
      value: 'top-rated-japan-movies',
      label: '🇯🇵 Top Rated in Japan',
      description: 'Top rated movies released in Japan',
      config: {
        type: 'movie',
        sortBy: 'rating',
        region: 'JP',
        name: 'IMDB Top Rated Japan Movies',
      },
    },
    {
      value: 'top-rated-korea-movies',
      label: '🇰🇷 Top Rated in South Korea',
      description: 'Top rated movies released in South Korea',
      config: {
        type: 'movie',
        sortBy: 'rating',
        region: 'KR',
        name: 'IMDB Top Rated Korea Movies',
      },
    },
  ],
  series: [
    {
      value: 'top-rated-series',
      label: '⭐ IMDB Top Rated Series',
      description: 'Top rated TV series from IMDB dataset',
      config: { type: 'series', sortBy: 'rating', name: 'IMDB Top Rated Series' },
    },
    {
      value: 'most-voted-series',
      label: '🗳️ Most Voted Series',
      description: 'Most voted TV series on IMDB',
      config: { type: 'series', sortBy: 'votes', name: 'IMDB Most Voted Series' },
    },
    {
      value: 'top-rated-india-series',
      label: '🇮🇳 Top Rated in India',
      description: 'Top rated TV series released in India',
      config: {
        type: 'series',
        sortBy: 'rating',
        region: 'IN',
        name: 'IMDB Top Rated India Series',
      },
    },
    {
      value: 'top-rated-japan-series',
      label: '🇯🇵 Top Rated in Japan',
      description: 'Top rated TV series released in Japan',
      config: {
        type: 'series',
        sortBy: 'rating',
        region: 'JP',
        name: 'IMDB Top Rated Japan Series',
      },
    },
    {
      value: 'top-rated-korea-series',
      label: '🇰🇷 Top Rated in South Korea',
      description: 'Top rated TV series released in South Korea',
      config: {
        type: 'series',
        sortBy: 'rating',
        region: 'KR',
        name: 'IMDB Top Rated Korea Series',
      },
    },
  ],
};
